/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tools;

import java.awt.Color;
import java.awt.Graphics2D;

/**
 *
 * @author DELL
 */
public class GraphicsXY extends javax.swing.JFrame {

    /**
     * Creates new form GraphicsXY
     */
    public GraphicsXY() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        pnlDraw = new javax.swing.JPanel();
        btnDraw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        pnlDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDrawMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlDrawLayout = new javax.swing.GroupLayout(pnlDraw);
        pnlDraw.setLayout(pnlDrawLayout);
        pnlDrawLayout.setHorizontalGroup(
            pnlDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pnlDrawLayout.setVerticalGroup(
            pnlDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(pnlDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 300, 300));

        btnDraw.setText("Draw");
        btnDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawActionPerformed(evt);
            }
        });
        getContentPane().add(btnDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        setBounds(0, 0, 656, 488);
    }// </editor-fold>//GEN-END:initComponents

     private void drawAxis(){
         //Generate  points  for  y = 0.1 *  x 
        Graphics2D g = (Graphics2D) pnlDraw.getGraphics();
        
        g.setColor(new Color(50,90,0));
       // g.setColor(Color.white);
        g.fillRect(0,0,300,300);
        
        
        //g.setColor(new Color(1,0,0));
         g.setColor(Color.white);
         // g.drawRect (0,0,300,300);
         
         
         //draw x axis , from (0,0) yo (20,0)
         
       g.drawLine(
            Coordinate.toScreenX(Coordinate.XMAX),
            Coordinate.toScreenY(0.0f),
            Coordinate.toScreenX(Coordinate.XMAX),
            Coordinate.toScreenY(0.0f)
        );
        
        
        for(float dx = Coordinate.XMIN; dx < Coordinate.XMAX; dx +=1.0 ){
            g.drawLine(
                Coordinate.toScreenX(dx),
                Coordinate.toScreenY(0),
                Coordinate.toScreenX(dx),
                Coordinate.toScreenY(0.5f)
            );
                    
        }
        
        g.drawLine(
            Coordinate.toScreenX(0.05f),
            Coordinate.toScreenY(0),
            Coordinate.toScreenX(0.05f),
            Coordinate.toScreenY(20.0f)
        );
        
        
        for(float dy = 0; dy < Coordinate.YMAX; dy +=1.0 ){
            g.drawLine(
                Coordinate.toScreenX(0),
                Coordinate.toScreenY(dy),
                Coordinate.toScreenX(0.5f),
                Coordinate.toScreenY(dy)
            );
                    
        }
     }
    
        private void  drawFunction(){
            //Generate  point for y = 0.1 * x^2
            //Draw points
            
            int nPoints = 100;
            //float dx = Coordinate.XMAX/nPoints;
            float dx =  (Coordinate.XMAX - Coordinate.XMIN)/nPoints;
            
            float x[] = new float [nPoints];
            float y[] = new float [nPoints];
            
            float dy[] = new float[nPoints];
            float Iy[] = new float[nPoints];
            
            
            for(int i = 0; i < nPoints; i++ ){
                x[i] =  i*dx;
                y[i] = 0.1f * x[i] * x[i];
                dy[i] = 0.2f * x[i];
                Iy[i] =  0.0333f * x[i] * x[i];
            }
            
            
            
            
            //Draw  function points
            Graphics2D g = (Graphics2D) pnlDraw.getGraphics();
            
            g.setColor(Color.white);
            
            for(int i = 0; i < nPoints -1 ; i++){
                g.drawLine(
                Coordinate.toScreenX(x[i]),
                Coordinate.toScreenY(y[i]),
                Coordinate.toScreenX(x[i+1]),
                Coordinate.toScreenY(y[i+1])
            );
                
            }
            
            g.setColor(Color.yellow);
            
            for(int i = 0; i < nPoints -1 ; i++){
                g.drawLine(
                Coordinate.toScreenX(x[i]),
                Coordinate.toScreenY(dy[i]),
                Coordinate.toScreenX(x[i+1]),
                Coordinate.toScreenY(dy[i+1])
            );
                
            }
            
            
             g.setColor(Color.red);
            
            for(int i = 0; i < nPoints -1 ; i++){
                g.drawLine(
                Coordinate.toScreenX(x[i]),
                Coordinate.toScreenY(Iy[i]),
                Coordinate.toScreenX(x[i+1]),
                Coordinate.toScreenY(Iy[i+1])
            );
                
            }
        }
             
     
    private void pnlDrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDrawMouseClicked
        // TODO add your handling code here:
        drawAxis();
        drawFunction();
        
    }//GEN-LAST:event_pnlDrawMouseClicked

    private void btnDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawActionPerformed
        // TODO add your handling code here:
        drawAxis();
        drawFunction();
        
    }//GEN-LAST:event_btnDrawActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicsXY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicsXY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicsXY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicsXY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicsXY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDraw;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlDraw;
    // End of variables declaration//GEN-END:variables
}
